name: path_planning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - scipy
  - matplotlib
  - networkx
  - ipython
  - pip
  - yaml
  - pip:
      - gymnasium
      - shapely
